name: NPM Publish

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - name: Build types
        run: npm run build-types
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  notify-slack:
    needs: publish-npm
    uses: janis-commerce/.github/.github/workflows/slack-notify-publish.yml@master
    with:
      username: API Get
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
