name: NPM Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: janis-commerce/.github/.github/workflows/npm-publish.yml@master
    with:
      build-types: true
      slack-username: API Get
    secrets:
      npm_token: ${{ secrets.npm_token }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
